version: '3'
services:
  server1:
    image: server
    environment:
      - APP=server1
    ports:
      - "8081:5000"
  server2:
    image: server
    environment:
      - APP=server2
    ports:
      - "8082:5000"
  server3:
    image: server
    environment:
      - APP=server3
    ports:
      - "9081:5000"
  server4:
    image: server
    environment:
      - APP=server4
    ports:
      - "9082:5000"